feat(app): improve error messaging when Fastly servers are unresponsive (#1212)
* Handle Fastly API unresponsiveness Errors on Authentication

When Fastly servers are unresponsive (indicated by a 5xx response), the CLI currently shows a cryptic error message due to unexpected values in the response body (e.g., unable to parse body as JSON).

The last incident caused the CLI to display:

> ERROR: failed to configure authentication processes: failed to unmarshal OpenID Connect .well-known metadata: invalid character 'I' looking for beginning of value

The 'I' referred to the "Internal Server Error" in the response body, which is unclear/unactionable from a user perspective.

This change introduces a validation to handle this specific scenario:

If the authentication request returns a 5xx status code, it is now recognized as an error. The CLI will display a more actionable message, informing clients that the error is likely due to an outage or incident on the Fastly side. Clients can then check the status page or contact support.

Context:
* https://github.com/fastly/cli/issues/1210
* https://www.fastlystatus.com/incident/376536

* fix(app): use %d for int type

* fix(app): read body for use in error response

* refactor(app): use http constant

* fix(app): write valid code

---------

Co-authored-by: Marcelo Boeira <marcelo@boeira.me>