Allow usage of Rust 1.91.1 and later patch releases (#1576)
### Change summary

Rust 1.91.1 includes a fix for the incompatibility which appeared in
1.91.0. The CLI will now allow usage of that version, and any later
patch releases in 1.91.x, but not 1.92 or later. A future CLI version
will support 1.92 once beta releases of that version have been tested.

 All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull
Requests](https://github.com/fastly/cli/pulls) for the same
update/change?

Example output when Rust 1.91.0 is used:
```
kpfleming@kpfleming:~/src/fastly/http-me$ ~/src/fastly/cli/fastly compute build
✓ Verifying fastly.toml
✓ Identifying package name
✓ Identifying toolchain

ERROR: version '1.91.0' of Rust is not compatible with Fastly Compute.

Consult the Rust guide for Compute at https://www.fastly.com/documentation/guides/compute/rust/ for more information.
```