Basic support for historical & realtime stats (#66)
* Make run_test use cmp.Diff for output comparison

This gives a lot more context on what's going wrong with output.
cmp is already in the tree, so this isn't a new dependency.

Failing test output now looks like:

    --- FAIL: TestApplication/help_argument_only (0.00s)
        run_test.go:75: output mismatch (-want +got):   []string{
              	... // 579 identical elements
              	"-n, --name=NAME              The name of the S3 logging object",
              	"",
            - 	"stats regions",
            - 	"List stats regions",
            - 	"",
            - 	"",
              	"stats historical [<flags>]",
              	"Query historical stats",
              	... // 13 identical elements
              }

* Initial add of "stats" command tree and "stats regions"

* Initial add of "stats historical"

* Initial add of "stats realtime"

* Rename stats source files to match convention

* Use EnumVar for stats flag checking, rather than checkArgs

* Incorporate review feedback on stats command parsers

* Parse stats command flags directly into input structs
* Improve some message strings

* Switch to our cmp.Diff helper for run_test output checks

* Add tests for "stats regions" and "stats historical"

* Resolve lint errors

* Remove an unused manifest in HistoricalCommand (staticcheck)

* Scratch that, use it even more.

* Make --service-id a required argument to "stats historical"

* Fix JSON unmarshaling when only one service-id is in the mix

* Fix the tests too